from .nxdify_node import (
    NODE_CLASS_MAPPINGS as NXDIFY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NXDIFY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .minimax_autoprompt_nodes import (
    NODE_CLASS_MAPPINGS as MINIMAX_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MINIMAX_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **NXDIFY_NODE_CLASS_MAPPINGS,
    **MINIMAX_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NXDIFY_NODE_DISPLAY_NAME_MAPPINGS,
    **MINIMAX_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

